### ISSUE TITLE
feature/add-env-file-firebase

### ISSUE THREAD

**Issue by AnthonyQuispe** [AnthonyQuispe/SpicyNuggs#5]
#### Overview  
Set up a `.env` file to securely store Firebase configuration keys and ensure sensitive information is excluded from the repository. This step is crucial for protecting the Firebase project's API keys and other credentials. Additionally, for deployment through GitHub Actions, Firebase configuration will be stored in GitHub Secrets to securely pass environment variables during the build and deployment process.

#### Acceptance Criteria  
- Create a `.env` file in the root directory.  
- Store Firebase configuration keys as environment variables.  
- Add `.env` to `.gitignore` to prevent it from being committed to the repository.  
- Update the `firebase.js` file to use environment variables for configuration.  
- Configure GitHub Secrets for deployment.  
- Test to ensure the app runs without errors after replacing hardcoded values with environment variables.

#### Tasks  
1. **Create `.env` File**  
   - Add the following keys to the `.env` file:  
     ```env  
     REACT_APP_FIREBASE_API_KEY=your-api-key  
     REACT_APP_FIREBASE_AUTH_DOMAIN=your-auth-domain  
     REACT_APP_FIREBASE_PROJECT_ID=your-project-id  
     REACT_APP_FIREBASE_STORAGE_BUCKET=your-storage-bucket  
     REACT_APP_FIREBASE_MESSAGING_SENDER_ID=your-sender-id  
     REACT_APP_FIREBASE_APP_ID=your-app-id  
     ```  

2. **Update `.gitignore`**  
   - Add `.env` to the `.gitignore` file to ensure it is excluded from the repository:  
     ```gitignore  
     # Environment Variables  
     .env  
     ```  

3. **Modify Firebase Initialization**  
   - Update `src/utils/firebase.js` to use environment variables:  
     ```javascript  
     const firebaseConfig = {  
       apiKey: process.env.REACT_APP_FIREBASE_API_KEY,  
       authDomain: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,  
       projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID,  
       storageBucket: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,  
       messagingSenderId: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,  
       appId: process.env.REACT_APP_FIREBASE_APP_ID,  
     };  
     ```  

4. **Configure GitHub Secrets for Deployment**  
   - Go to **GitHub Settings** > **Secrets and variables** > **Actions** in your repository.  
   - Add the following secrets to store Firebase configuration:  
     - `REACT_APP_FIREBASE_API_KEY`  
     - `REACT_APP_FIREBASE_AUTH_DOMAIN`  
     - `REACT_APP_FIREBASE_PROJECT_ID`  
     - `REACT_APP_FIREBASE_STORAGE_BUCKET`  
     - `REACT_APP_FIREBASE_MESSAGING_SENDER_ID`  
     - `REACT_APP_FIREBASE_APP_ID`  

   - **Add `FIREBASE_TOKEN` secret** (generated via `firebase login:ci`) for Firebase deployment authentication.

5. **Create GitHub Actions Workflow for Firebase Deployment**  
   - Add the following to `.github/workflows/deploy.yml` to deploy to Firebase Hosting using the configured secrets:  
     ```yaml
     name: Deploy to Firebase Hosting

     on:
       push:
         branches:
           - main

     jobs:
       deploy:
         runs-on: ubuntu-latest

         steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
             node-version: '16'

         - name: Install dependencies
           run: npm install

         - name: Build the project
           env:
             REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
             REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
             REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
             REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
             REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
             REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
           run: npm run build

         - name: Deploy to Firebase Hosting
           env:
             FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
           run: npx firebase deploy --only hosting
     ```

6. **Verify Functionality**  
   - Test the app locally to ensure Firebase connects without errors using the environment variables.  
   - Run the GitHub Actions workflow by pushing to the `main` branch and verify the deployment.

7. **Commit and Push**  
   - Commit the updated `firebase.js` file and `.gitignore` file (do not include `.env`).  

#### Resources  
- [Environment Variables in React](https://create-react-app.dev/docs/adding-custom-environment-variables/)  
- [Firebase for Web Documentation](https://firebase.google.com/docs/web/setup)  
- [GitHub Actions](https://docs.github.com/en/actions)  
- [Firebase CI Token](https://firebase.google.com/docs/cli#auth-emulator)  

#### Priority  
High - Necessary to securely manage sensitive Firebase credentials and automate deployment.  

#### Definition of Done  
- `.env` file is created and configured with Firebase keys.  
- `.env` is ignored in the repository using `.gitignore`.  
- Firebase configuration is stored in GitHub Secrets for deployment.  
- GitHub Actions workflow is set up and deploys the app successfully to Firebase Hosting.  
- Code is pushed to the `feature/add-env-file-firebase` branch.  
- Pull Request is created for review.
