### ISSUE TITLE
feature/setup-github-actions-ci-cd

### ISSUE THREAD

**Issue by AnthonyQuispe** [AnthonyQuispe/SpicyNuggs#6]
#### Overview  
Set up continuous integration (CI) and continuous deployment (CD) using GitHub Actions. This will automate the process of testing, building, and deploying the Spicy Nuggs website. The goal is to ensure that every push to the `main` branch triggers an automatic build, testing, and deployment pipeline. This will increase efficiency and ensure that the app is always up to date in production.

#### Acceptance Criteria  
- Create a `.github/workflows/ci-cd.yml` file to define the CI/CD pipeline.  
- Include steps for setting up Node.js, installing dependencies, running tests, building the project, and deploying to Firebase Hosting.  
- Ensure that each push to the `main` branch automatically triggers the CI/CD pipeline.  
- The pipeline should run on every pull request and push to `main`.  
- Implement a mechanism to handle Firebase deployment using GitHub Secrets securely.

#### Tasks  
1. **Create GitHub Actions Workflow File**  
   - Create a new file at `.github/workflows/ci-cd.yml`.  
   - Add the following content to set up the basic CI/CD pipeline:  
   
     ```yaml
     name: CI/CD Pipeline

     on:
       push:
         branches:
           - main
       pull_request:
         branches:
           - main

     jobs:
       ci:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout Code
             uses: actions/checkout@v3

           - name: Set up Node.js
             uses: actions/setup-node@v3
             with:
               node-version: '16'

           - name: Install Dependencies
             run: npm install

           - name: Run Linter
             run: npm run lint

           - name: Run Tests
             run: npm run test --if-present

           - name: Build Project
             run: npm run build

       cd:
         runs-on: ubuntu-latest
         needs: ci
         steps:
           - name: Checkout Code
             uses: actions/checkout@v3

           - name: Set up Node.js
             uses: actions/setup-node@v3
             with:
               node-version: '16'

           - name: Install Dependencies
             run: npm install

           - name: Deploy to Firebase Hosting
             env:
               FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
               REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
               REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
               REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
               REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
               REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
               REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
             run: |
               npm run build
               npx firebase deploy --only hosting
     ```

2. **Set up CI Steps**  
   - **Install Dependencies**: This step will install the required dependencies using `npm install`.  
   - **Run Linter**: Add a linting step to check the code style with `npm run lint` (if you have linting configured).  
   - **Run Tests**: Add a step to run tests with `npm run test` (if applicable).  
   - **Build Project**: The `npm run build` command will be run to ensure the project is built correctly.

3. **Set up CD Steps**  
   - **Deploy to Firebase Hosting**: The deployment step will use Firebase CLI to deploy the app to Firebase Hosting. Firebase secrets will be securely accessed using GitHub Secrets.  
   - The environment variables for Firebase configuration (`REACT_APP_FIREBASE_*`) will be set from the GitHub Secrets.

4. **Test CI/CD Workflow**  
   - Make a small change in the repository and push it to the `main` branch.  
   - Verify the GitHub Actions pipeline is triggered.  
   - Check the logs for any errors and ensure the deployment process works as expected.

5. **Add Firebase Token to GitHub Secrets**  
   - Generate a Firebase token for CI/CD using the Firebase CLI:  
     ```bash
     firebase login:ci
     ```  
   - Add the generated token as a GitHub secret: `FIREBASE_TOKEN`.

6. **Commit Changes**  
   - Commit the newly created `.github/workflows/ci-cd.yml` file to the repository and push it to GitHub.

#### Resources  
- [GitHub Actions Documentation](https://docs.github.com/en/actions)  
- [Firebase Hosting Deployment](https://firebase.google.com/docs/hosting/github-integration)  
- [GitHub Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets)  
- [Firebase CI Token Setup](https://firebase.google.com/docs/cli#auth-emulator)  

#### Priority  
High - Automating the deployment process using CI/CD is essential to maintain a fast and efficient development cycle.

#### Definition of Done  
- `.github/workflows/ci-cd.yml` is created and configured for CI/CD.  
- GitHub Actions successfully runs on pushes and pull requests to `main`.  
- Firebase Hosting deployment is successful and triggered by the workflow.  
- Linting and tests are run before deploying.  
- The workflow is tested, and any issues are resolved.  
- Code is committed and pushed to the `feature/setup-github-actions-ci-cd` branch.  
- Pull Request is created for review.
